name: Nightclub2.0
version: '${project.version}'
main: com.ilm9001.nightclub.Nightclub
api-version: 1.17
authors: [ ilm9001 ]
description: Nightclub 2.0

commands:
  light:
    description: light builder + editor
    usage: /light
    permission: nightclub.light

permissions:
  nightclub.light:
    description: Access to /light which is the builder and editor
    default: op